/**
 * SPaG generator-family SIGN-OFF (annie's SPaG signing sitting).
 * `pnpm --filter @cluecrew/db exec dotenv -e ../../.env -- tsx ../../scripts/apply-spag-signatures.ts`
 *
 * Records a reviewer SIGNATURE per SPaG family via the written-review path (append-only
 * AttributionEvent, action SIGNED, actor current-reviewer). The M-place pattern: the
 * qualification sits WITH the signature, not in a side note — annie signs that every item the
 * family emits is fair at its tier and the ladder is honest, NOT that a child can practise it
 * without repetition (the bank is 24 sentences, 6 per rung, so a tier emits six distinct items).
 */
import { prisma } from '../packages/db/src/index';

const DAVID = 'human:david@cluecrew.test';
const METHOD = 'written review — SPaG signing sitting 2026-08-08';

// [familyId, signed scope, note]
const SIGNATURES: Array<[string, string, string]> = [
  ['spag-spell-homophone-by-sound', 'T1–T4', 'Homophones. TRAP DEFINITION: a part is a near-miss iff a word in it is a standard KS2 homophone (a reviewed list — "is a homophone" has no generative rule); weak-forms/near-homophones/low-frequency (were/we\'re, shore/sure, thyme) excluded. SIGNED AS: every item the family emits is a fair item at its tier and the near-miss ladder (0/1/2/3, derived-and-verified) is honest — NOT that a child can practise without repetition. DEPTH: 24 verified sentences (6/rung) → six distinct items per tier, so two sittings exhaust a tier; a SERVING concern to size before volume (M-place shape). T5 out of scope (SPaG ceiling T4).'],
  ['spag-spell-unstressed-suffix-vowel', 'T1–T4', 'Unstressed suffix vowel. TRAP DEFINITION: a near-miss iff a word (≥6 letters) ends -ent/-ant, -ence/-ance, -able/-ible or -ary/-ery/-ory — an unstressed suffix vowel with no sound to guide it (necessary, category, memory). SIGNED AS: every item fair at its tier; ladder = near-miss 0/1/2/3, derived-and-verified; N-keyed at rung-1. DEPTH: 24 sentences (6/rung). T5 out of scope.'],
  ['spag-spell-silent-letter-dropped', 'T1–T4', 'Silent letters. TRAP DEFINITION: membership in the reviewed 36-word KS2 silent-letter list — no generative rule exists ("do children omit it" is empirical); right/light/walk/would EXCLUDED, knight/island/knock/autumn IN. SIGNED AS: every item fair at its tier; ladder 0/1/2/3; rung-3 traps cross-group so items read as sentences not kn-drills. DEPTH: 24 sentences (6/rung). T5 out of scope.'],
  ['spag-spell-double-consonant-boundary', 'T1–T4', 'Double letters. TRAP DEFINITION: membership in the reviewed ~30-word pool of prefix/suffix-boundary and INERT doubles (removing the double would not change the sound — necessary, embarrass, accommodate); AUDIBLE short-vowel doubles (summer, little, happens) excluded. KEYS restricted to child-used words; the wider pool serves only as traps. SIGNED AS: every item fair at its tier; ladder 0/1/2/3; N-keyed at rung-1. DEPTH: 16 sentences (4/rung) → FOUR items per tier, so a child exhausts the family in one sitting; SIZE BEFORE SERVING (the tightest depth of the four, M-place shape).'],
  ['spag-punct-apostrophe-contraction', 'T1–T3', 'Apostrophe (contraction), SPOT-THE-MISTAKE. its/it\'s, they\'re/their/there, you\'re/your, we\'re/were, who\'s/whose — UNARGUABLE (one form right, one wrong). TRAP: a part with a contraction-set word (either form), a reviewed word LIST (fourth no-rule case), apostrophes stripped in the lookup. PAIR-CORRECTNESS: every set-member in a CLEAN part must be the correct form for that sentence (a contraction trap word can be genuinely wrong — they\'re with no plural referent), reviewed per sentence as nmVerified and CI-checked to equal the lookup\'s clean-part flags. SIGNED AS: every item fair; ladder 0/1/2 → T1–T3; N-keyed at rung-1 shows all-correct forms. DEPTH: 11 keys, 3–4/tier — the SMALLEST family (the confusion set is only eleven words; its/it\'s is the value not the volume), exhausted in one sitting; SIZE BEFORE SERVING.'],
  ['spag-punct-apostrophe-possessive', 'T1–T3', 'Apostrophe (possessive) — the REFRAME "which part needs an apostrophe" (spot-form dies: a noun-modifier is permissive, `the girls coats` has three readings). THREE parts + N; typing reviewed per sentence. R-WELL = TWO well types only, by the AS-PRESENTED TEST (a required site must be unambiguous with the apostrophe STRIPPED, not once corrected): proper name (`Toms bike` — `Toms` is not a word) and irregular plural (`The childrens shoes` — `childrens` is not a word). The singular-determiner type FAILS stripped (`the girls purse` = girl\'s / girls\' / plural) and was dropped. Names are themselves checked against their own plurals (`Marks bike`, `Roses hat` would fail). O = a NATURAL ATTRIBUTIVE only (`the teachers lounge`); a CONCRETE possession is never O (it would be a second required answer). ONE merged O-tag `en-apostrophe-attributive` (modifier number is a parameter, not a second misconception). SIGNED AS: every item fair; ladder = attributive-count 0/1/2 → T1–T3. DEPTH: 13 sentences, 4/tier; SIZE BEFORE SERVING. Keys A4/B2/C4/N3 — no positional cue. KNOWN GAP: the plural-possessive-PLACEMENT child (`girls\' coats`) is out of scope for this family — reaching her needs a concrete-possession site, which is a second answer; v2 frame is "which is correct: girl\'s / girls\' / girls?".'],
  ['spag-punct-terminal-boundary', 'T1–T3', 'Terminal and boundary, SPOT-FORM, TWO error types. RUN-ONS DROPPED: the missing full stop sits at a part JOIN, so nothing is wrong inside either part and a child naming the second has reasoned identically to one naming the first — a defensible wrong answer with no location. KEPT: comma SPLICE (long non-parallel clauses; short parallel ones excluded because a child cannot judge parallelism, which is not on the curriculum) and FRAGMENT after a subordinator — both put a visible mark INSIDE a part. TRAP = a REQUIRED comma only (fronted subordinate clause, or list-internal); semicolons and comma-plus-coordinator are punctuation CHOICES and appear nowhere in the bank — the build fails if a choice reaches a clean part. Correct full stops stay PLAIN (a rule, not a choice). SIGNED AS: every item fair; ladder 0/1/2 → T1–T3 (rung 3 needs three required-comma parts in one item, which does not occur without strain). DEPTH: 12 sentences, 4/rung; exhaustible in a sitting; SIZE BEFORE SERVING.'],
  ['spag-punct-speech', 'T1–T4', 'Speech punctuation, SPOT-FORM, TWO error types. MISSING-OPENING DROPPED: with the opening mark gone the stray closing mark is the only evidence of direct speech, so the correction is undetermined (add an opening mark, or delete the closing one and read it as reported speech) — both defensible. KEPT: missing CLOSING (the opening mark and the comma before it establish direct speech, so closing is the only correction) and missing CAPITAL. TRAP = a reporting-verb part carrying NO marks, so no clean part holds a quote boundary. NO N OPTION at any rung — an N item would need a closed quotation in a clean part, carrying terminal-at-boundary, which British usage argues both ways; consequences: en-n-option-avoidance is unreachable here and the guessing rate is 1 in 4. Platform convention, settled: terminal punctuation sits INSIDE the closing mark. SIGNED AS: every item fair; ladder 0/1/2/3 → T1–T4. DEPTH: 16 sentences, 4/rung; exhaustible in a sitting.'],
  ['spag-punct-comma-needs', 'T1–T3', 'Commas — the REFRAME "which part NEEDS a comma" (spot-the-mistake rests on "no comma acceptable here", nearly empty at phrase boundaries). THREE parts + N; site typing REVIEWED per sentence (the third no-rule case): R = fronted subordinate clause or list-internal comma (beyond argument); O = optional (trailing PP/adverb, serial slot, TRAILING subordinate clause, coordinator joining clauses); F = tight bond. Key = the R part or N. SIGNED AS: every item fair; ladder = optional-count 0/1/2 → T1–T3 (three parts cannot hold three O plus a main verb, so no T4 — an honest ceiling). MIRRORED PAIRS sanctioned (fronted/trailing, rungs 0/1) — never same child same session. DEPTH: 21 sentences (~7/tier), exhaustible in two sittings; SIZE BEFORE SERVING. A is modal (fronted clauses key A by the rule) — inherent, not a bug.'],
  ['spag-cloze-word-class', 'T2', 'Word class by job, CLOZE. No N option (in a gap-fill one option is better by construction). Deciding factor declared and typed on every item: GRAMMAR (the slot requires one word class); register and collocation are forbidden (R18). Distractors are the same root in other classes — the error itself. SIGNED AS: every item fair at T2. SINGLE TIER: only one form fits a slot, and where two co-parse (kind/kindly) both are acceptable, so the parse-count ladder cannot climb — an honest ceiling, not a gap. DEPTH: 6 items.'],
  ['spag-cloze-tense', 'T2 + T4', 'Tense sequence, CLOZE. No N option. Every item declares factor GRAMMAR and NAMES its forcing marker — the factor must be forcing, not merely preferable, or "grammar" is over-claimed. T2 = a definite-past marker (Yesterday, Last week, Two days ago) rules out the other three; T4 = TWO options parse and syntax decides, on the only two patterns that genuinely force: coordination with a past-simple verb, and "by the time" + a completed prior event. THE T3 GAP IS CORRECT — a rung there would need a tense that is preferable rather than forced, which R18 forbids. Three proposed widenings were REJECTED on that test (before/after + past perfect are stylistic; "already" forces but yields one parse, a T2 shape). DEPTH: 8 at T2, 7 at T4.'],
  ['spag-cloze-connectives', 'T3', 'Connectives, CLOZE. SPLIT from question tags (R18) — they sit at opposite ends of the parse ladder and test different skills: connectives are meaning, tags are syntax, and a child can be strong at one and weak at the other. No N option. Factor SENSE on every item: all four options parse, so the child judges the logical relation (cause, contrast, consequence, alternative, sequence) unaided — safe, because "we stayed inside but it was raining" is wrong, not merely worse. SINGLE TIER at the top of the parse ladder. DEPTH: 6 items.'],
  ['spag-cloze-tags', 'T2', 'Question tags, CLOZE. Split from connectives. Factor GRAMMAR: the tag must match subject, auxiliary and polarity, so only one option parses. TIER IS A PREDICTION, NOT A FINDING (annie, 2026-08-08): matching three features sounds harder than one slot, but the child is SELECTING, not deriving — are you / isn\'t it / don\'t you are audibly wrong to a native speaker before analysis, and tags are among the last things a native speaker gets wrong in speech (the vr-04 problem mirrored: difficulty that looks like content and is absent in practice). If serving data shows T3-rate failure, MOVE IT — that is the signature working as intended, not being overturned. DEPTH: 8 items, deliberately unpadded — eight is the whole realistic space of subject-auxiliary-polarity combinations a Year 5 child meets.'],
  ['en-vocab-in-context', 'T2–T4', 'Vocabulary in context (route a + the Mode B rare-sense route). THE FLIP: T2 tests the FAMILIAR sense with the rarer as the trap; T3–T4 test the rarer sense. Without it the family only ever asks "do you know the second meaning?", when the skill is LETTING THE SENTENCE TELL YOU WHICH MEANING IS LIVE — a child who learned the trick scored 16/18 without reading. Checkable: tier <= 2 iff familiar. THE GUARD: a familiar item exists only where the headword is itself in reach (vault tier <= 2); otherwise she is asked whether she has met the word at all, which no sentence-reading rescues (warrant at T2 showed it). T1 FLOOR IS A VAULT PROPERTY, NOT A GAP: only 3 of 23 Mode A cards sit at vault T1, because a word must be common enough to be known TWICE OVER — do not hunt for words that do not exist. DEPTH 41: T2 9 / T3 11 / T4 21; the district\'s largest single T4 contributor. SERVING: the two items from one card share a pairId and must NEVER reach the same child. FILLER PLAUSIBILITY WAS CHECKED BY HAND — no instrument can check it (the form audit sees form only, and threw 5 false positives to 3 real catches).'],
];

async function main(): Promise<void> {
  for (const [familyId, scope, note] of SIGNATURES) {
    const id = `sig-${familyId}-2026-08-08`;
    await prisma.attributionEvent.upsert({
      where: { id },
      create: { id, recordType: 'spag-template-family', recordId: familyId, action: 'SIGNED', actor: 'current-reviewer', recordedBy: DAVID, field: `generator@${scope}`, note, method: METHOD },
      update: { field: `generator@${scope}`, note, method: METHOD },
    });
    console.log(`SIGNED ${familyId} @ ${scope}`);
  }
  const n = await prisma.attributionEvent.count({ where: { recordType: 'spag-template-family', action: 'SIGNED' } });
  console.log(`\n${n} SPaG family signature(s) on record.`);
  await prisma.$disconnect();
}

void main();
