/**
 * EXPORT PILOT CONTENT TO ~/DOWNLOADS FOR COWORK — `pnpm export:pilot`
 *
 * The Downloads copy is GENERATED, never canonical. It exists so Cowork can read the current
 * pilot state; it is never a place anyone — this repo's scripts, David, or an agent — writes a
 * ruling to directly. If a ruling needs applying, it goes through `scripts/lib/pilot-review.ts`
 * against `content/pilot-review/`, and this export re-runs afterward.
 *
 * Every delivered copy carries a banner making its status impossible to miss.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { readPilotFile } from './lib/pilot-review';
import { artefactStamp, deliver, stampedName } from './lib/export-destination';

const OUT_DIR = '/Users/davidb/Downloads/11+/from-cluecrew';
const FILES = ['ENG-004-anne-green-gables.json'] as const;

function main(): void {
  mkdirSync(OUT_DIR, { recursive: true });
  for (const filename of FILES) {
    const batch = readPilotFile(filename);
    const generatedAt = new Date().toISOString();
    const stamp = artefactStamp(batch, generatedAt, 'mixed', `pilot batch ${filename}, generated from content/pilot-review — read-only`);
    const family = filename.replace(/\.json$/, '');
    const base = stampedName(family, stamp.sourceHash, 'json');
    const path = `${OUT_DIR}/${base}`;
    writeFileSync(
      path,
      JSON.stringify(
        {
          kind: 'pilot-export',
          _READ_ONLY:
            'GENERATED FROM content/pilot-review — DO NOT EDIT THIS FILE. A ruling applied here does ' +
            'nothing: it is not read back into the repo. Apply rulings through the sanctioned pilot ' +
            'pipeline (scripts/lib/pilot-review.ts) against the canonical copy, then re-export.',
          ...stamp,
          batch,
        },
        null,
        2,
      ),
    );
    deliver(path, family);
    console.log(`  exported ${filename} → ${base}`);
  }
}

main();
